[package]
name = "LXMF-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
ed25519-dalek = "2.2"
sha2 = "0.10"
rmp-serde = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"

[dependencies.reticulum]
git = "https://github.com/doubleailes/Reticulum-rs"
branch = "LXMF"
